version: 2.1
orbs:
  snyk: snyk/snyk@0.0.10
jobs:
  build-test:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: 'sudo npm install -g'
      - run:
          name: "Build"
          command: 'npm run build'
      - run:
          name: "Test"
          command: 'npm test'
      - snyk/scan:
          fail-on-issues: true
          monitor-on-build: false
          token-variable: SNYK_TOKEN
  build-test-monitor:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: 'sudo npm install -g'
      - run:
          name: "Build"
          command: 'npm run build'
      - run:
          name: "Test"
          command: 'npm test'
      - snyk/scan:
          fail-on-issues: true
          monitor-on-build: false
          token-variable: SNYK_TOKEN
  
  
workflows:
  version: 2.1
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-test-monitor:
          context: SNYK
          filters:
            branches:
              only: 
                - master
